spring.application.name=urlshortener


server.port=8080
# logging.level.org.springframework=INFO
spring.data.mongodb.uri=mongodb+srv://dhan_296:dhan2906@cluster0.tv1mmuq.mongodb.net/urlshortenerdb?retryWrites=true&w=majority
spring.data.mongodb.database=urlshortenerdb